### ISSUE TITLE
Cannot find dependency on Maven Central

### ISSUE THREAD

**Issue by armandino** [Mobe91/instancio-jpa#2]
Hi @Mobe91,

I tried to grab one of the dependencies from Maven Central, but neither `jakarta` nor `javax` seems to be there:

https://search.maven.org/search?q=instancio-jpa

Should it be available from Maven central or elsewhere?

**Comment by Mobe91** [comment]
Hi @armandino, that's right I have not created a release yet. Will probably do this week.

**Comment by Mobe91** [comment]
@armandino The first release should now be in Maven Central! 🥂 😄
